# docs.yml :: push pdoc documentation to github website 
name: docs

on:
  push:
    branches:
      - main

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install all dependencies (including pdoc)
      - run: pip install -e . && pip install pdoc
      
      # Build your documentation into pdocs/
      # Use negative regular expressions to suppress pdoc compilation for non .py files
      - run: pdoc --math -d numpy -o pdocs/ shapelets !shapelets.self_assembly._rdistance*

      - uses: actions/upload-pages-artifact@v3
        with:
          path: pdocs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
