# draft-pdf.yml :: create PDF according to Journal of Open Source Software template
name: draft-pdf

on:
    push:
      branches:
        - publications
    pull_request:
      branches:
        - publications

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: publications/2309_JOSS/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: publications/2309_JOSS/paper.pdf
